import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="bg-gradient-to-r from-purple-500 to-indigo-600 text-white p-4">
      <nav className="flex items-center justify-between">
        <h1 className="text-3xl font-extrabold">Your Website</h1>
        <ul className="flex space-x-4">
          <li>
            <Link to="/login" className="hover:text-gray-300">Login</Link>
          </li>
          <li>
            <Link to="/register" className="hover:text-gray-300">Register</Link>
          </li>
          <li>
            <Link to="/users" className="hover:text-gray-300">Users</Link>
          </li>
          <li>
            <Link to="/passwordrecoveryone" className="hover:text-gray-300">Password Recovery</Link>
          </li>
        </ul>
      </nav>
      <div className="mt-4">
        <h1 className="text-4xl font-extrabold mb-2">Welcome to Your Website!</h1>
        <p className="text-lg">
          This project was generated by <a href="https://www.dhiwise.com" className="text-blue-300 hover:underline">Dhiwise</a>. Quickly use the links above to navigate through all pages.
        </p>
      </div>
    </div>
  );
};

export default Home;
